import { Link } from "react-router";
import logo from "../images/logo.svg";

export function meta() {
    return [
        { title: "CryptoForge" },
        { name: "description", content: "Homepage" },
    ];
}

export default function Home() {
    return (
        <div className="flex flex-col items-center justify-center h-full w-full bg-white dark:bg-black text-black dark:text-white px-4">
            {/* Logo */}
            <div className="flex items-center mb-6">
                <img
                    src={logo} // generated by ChatGPT
                    alt="CryptoForge Logo"
                    style={{ height: 256, width: "auto" }}
                    className="mr-4"
                />
                <h1 className="text-4xl font-extrabold text-center">
                    Welcome to <span className="text-[#9172FF]">CryptoForge</span>
                </h1>
            </div>

            <p className="text-center text-lg text-gray-700 dark:text-gray-300 mb-6 max-w-2xl">
                Learn encryption like it's meant to be: manual, hands-on, and educational. CryptoForge puts you in the
                coder’s seat.
            </p>

            {/* Wrapper */}
            <div className="flex w-full gap-4 overflow-x-auto px-2">
                {/* Idea */}
                <div className="flex-1 min-w-[250px]">
                    <div className="collapse collapse-arrow bg-gray-400 dark:bg-gray-700 border-gray-500 dark:border-gray-600 border">
                        <input type="checkbox" />
                        <div className="collapse-title font-semibold">
                            Craft your own encrypted messages by hand
                        </div>
                        <div className="collapse-content text-sm">
                            Use a terminal-style interface to encrypt and decrypt your text.
                        </div>
                    </div>
                </div>

                {/* Algo */}
                <div className="flex-1 min-w-[250px]">
                    <div className="collapse collapse-arrow bg-gray-400 dark:bg-gray-700 border-gray-500 dark:border-gray-600 border">
                        <input type="checkbox" />
                        <div className="collapse-title font-semibold">Supported Algorithms</div>
                        <div className="collapse-content text-sm">
                            <ul className="list-disc list-inside">
                                <li><strong>Caesar Cipher</strong> – Simple letter shift</li>
                                <li><strong>Vigenère Cipher</strong> – Keyword-based substitution</li>
                                <li><strong>AES</strong> – Modern symmetric encryption (Advanced Encryption Standard)</li>
                                <li><strong>DES</strong> – Legacy symmetric encryption (Data Encryption Standard)</li>
                            </ul>
                        </div>
                    </div>
                </div>

                {/* Why */}
                <div className="flex-1 min-w-[250px]">
                    <div className="collapse collapse-arrow bg-gray-400 dark:bg-gray-700 border-gray-500 dark:border-gray-600 border">
                        <input type="checkbox" />
                        <div className="collapse-title font-semibold">Why Use CryptoForge?</div>
                        <div className="collapse-content text-sm">
                            <ul className="list-disc list-inside">
                                <li>Understand encryption, don’t just apply it</li>
                                <li>Practice encryption/decryption in a hands-on terminal environment</li>
                                <li>Have fun!</li>
                            </ul>
                        </div>
                    </div>
                </div>

                {/* Problem */}
                <div className="flex-1 min-w-[250px]">
                    <div className="collapse collapse-arrow bg-gray-400 dark:bg-gray-700 border-gray-500 dark:border-gray-600 border">
                        <input type="checkbox" />
                        <div className="collapse-title font-semibold">Have a Problem?</div>
                        <div className="collapse-content text-sm">
                            Visit the{" "}
                            <Link
                                to="/about#contact"
                                className="underline text-indigo-600 dark:text-[#9172FF] hover:text-indigo-800 hover:dark:text-indigo-600 transition"
                            >
                                Contact
                            </Link>{" "}
                            section to reach out to us. We’re here to help.
                        </div>
                    </div>
                </div>
            </div>

            {/* Buttons */}
            <div className="flex gap-4 mt-6">
                <Link
                    to="/tool"
                    className="px-6 py-2 rounded bg-[#9172FF] text-white dark:text-black font-medium hover:bg-indigo-600 transition"
                >
                    Go to the Terminal
                </Link>
                <Link
                    to="/about"
                    className="px-6 py-2 rounded bg-[#9172FF] text-white dark:text-black font-medium hover:bg-indigo-600 transition"
                >
                    Read More
                </Link>
            </div>
        </div>
    );
}